-- ----------------------------
-- Table structure for "FT_SHARES_ORDER"
-- ----------------------------
-- DROP TABLE "FT_SHARES_ORDER";
CREATE TABLE "FT_SHARES_ORDER" (
	"GMT_CREATE" VARCHAR2(32 BYTE) NULL ,
	"GMT_MODIFIED" VARCHAR2(32 BYTE) NULL ,
	"PROD_NAME" VARCHAR2(255 BYTE) NULL ,
	"PRICE" VARCHAR2(22 BYTE) NULL ,
	"STATUS" VARCHAR2(30 BYTE) NULL ,
	"TYPE" VARCHAR2(55 BYTE) NULL ,
	"TOTAL" VARCHAR2(22 BYTE) NULL ,
	"REMAINDER" VARCHAR2(22 BYTE) NULL ,
	"NUMBER_CODE" VARCHAR2(100 BYTE) NULL ,
	"ORI_PRICE" NUMBER(15,2) NULL ,
	"PHONE" NUMBER(11) NULL ,
	"HE_PHONE" NUMBER(11) NULL ,
	"SHARES_PROD_ID" VARCHAR2(100 BYTE) NULL ,
	"EVENT" VARCHAR2(200 BYTE) NULL ,
	"SHARES_ORDER_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN "FT_SHARES_ORDER"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "FT_SHARES_ORDER"."GMT_MODIFIED" IS '更新时间';
COMMENT ON COLUMN "FT_SHARES_ORDER"."PROD_NAME" IS '商品名称';
COMMENT ON COLUMN "FT_SHARES_ORDER"."PRICE" IS '价格';
COMMENT ON COLUMN "FT_SHARES_ORDER"."STATUS" IS '状态';
COMMENT ON COLUMN "FT_SHARES_ORDER"."TYPE" IS '类型';
COMMENT ON COLUMN "FT_SHARES_ORDER"."TOTAL" IS '总数';
COMMENT ON COLUMN "FT_SHARES_ORDER"."REMAINDER" IS '余数';
COMMENT ON COLUMN "FT_SHARES_ORDER"."NUMBER_CODE" IS '编号';
COMMENT ON COLUMN "FT_SHARES_ORDER"."ORI_PRICE" IS '原价';
COMMENT ON COLUMN "FT_SHARES_ORDER"."PHONE" IS '手机号';
COMMENT ON COLUMN "FT_SHARES_ORDER"."HE_PHONE" IS '对方手机号';
COMMENT ON COLUMN "FT_SHARES_ORDER"."SHARES_PROD_ID" IS '股票商品ID';
COMMENT ON COLUMN "FT_SHARES_ORDER"."EVENT" IS '事件';
COMMENT ON COLUMN "FT_SHARES_ORDER"."SHARES_ORDER_ID" IS 'ID';

-- ----------------------------
-- Indexes structure for table FT_SHARES_ORDER
-- ----------------------------

-- ----------------------------
-- Checks structure for table "FT_SHARES_ORDER"

-- ----------------------------

ALTER TABLE "FT_SHARES_ORDER" ADD CHECK ("SHARES_ORDER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "FT_SHARES_ORDER"
-- ----------------------------
ALTER TABLE "FT_SHARES_ORDER" ADD PRIMARY KEY ("SHARES_ORDER_ID");
