GO
/******  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE FT_SHARES_ORDER (
 		SHARES_ORDER_ID  nvarchar(100) NOT NULL,
		GMT_CREATE nvarchar(32) DEFAULT NULL,
		GMT_MODIFIED nvarchar(32) DEFAULT NULL,
		PROD_NAME nvarchar(255) DEFAULT NULL,
		PRICE nvarchar(22) DEFAULT NULL,
		STATUS nvarchar(30) DEFAULT NULL,
		TYPE nvarchar(55) DEFAULT NULL,
		TOTAL nvarchar(22) DEFAULT NULL,
		REMAINDER nvarchar(22) DEFAULT NULL,
		NUMBER_CODE nvarchar(100) DEFAULT NULL,
		ORI_PRICE numeric(15,2) NULL,
		PHONE int NOT NULL,
		HE_PHONE int NOT NULL,
		SHARES_PROD_ID nvarchar(100) DEFAULT NULL,
		EVENT nvarchar(200) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[SHARES_ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
